create table if not exists public.rhythm_states (
  user_key text primary key,
  user_id uuid references auth.users (id) on delete cascade,
  state jsonb not null,
  ui_state jsonb not null default '{}'::jsonb,
  schema_version integer not null default 1,
  client_updated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_rhythm_states_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists rhythm_states_updated_at on public.rhythm_states;
create trigger rhythm_states_updated_at
before update on public.rhythm_states
for each row
execute function public.set_rhythm_states_updated_at();

create index if not exists rhythm_states_client_updated_at_idx
on public.rhythm_states (client_updated_at desc);

alter table public.rhythm_states
add column if not exists user_id uuid references auth.users (id) on delete cascade;

drop index if exists public.rhythm_states_user_id_idx;
create unique index rhythm_states_user_id_idx
on public.rhythm_states (user_id);

alter table public.rhythm_states enable row level security;

drop policy if exists "rhythm_states_select_own_key" on public.rhythm_states;
drop policy if exists "rhythm_states_insert_own_key" on public.rhythm_states;

drop policy if exists "rhythm_states_select_authenticated" on public.rhythm_states;
create policy "rhythm_states_select_authenticated"
on public.rhythm_states
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "rhythm_states_insert_authenticated" on public.rhythm_states;
create policy "rhythm_states_insert_authenticated"
on public.rhythm_states
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "rhythm_states_update_authenticated" on public.rhythm_states;
create policy "rhythm_states_update_authenticated"
on public.rhythm_states
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "rhythm_states_update_own_key" on public.rhythm_states;

drop policy if exists "rhythm_states_delete_authenticated" on public.rhythm_states;
create policy "rhythm_states_delete_authenticated"
on public.rhythm_states
for delete
to authenticated
using ((select auth.uid()) = user_id);

create table if not exists public.rhythm_state_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  state jsonb not null,
  schema_version integer not null,
  created_at timestamptz not null default now()
);

create index if not exists rhythm_state_snapshots_user_created_idx
on public.rhythm_state_snapshots (user_id, created_at desc);

alter table public.rhythm_state_snapshots enable row level security;

drop policy if exists "rhythm_state_snapshots_select_authenticated" on public.rhythm_state_snapshots;
create policy "rhythm_state_snapshots_select_authenticated"
on public.rhythm_state_snapshots
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "rhythm_state_snapshots_delete_authenticated" on public.rhythm_state_snapshots;
create policy "rhythm_state_snapshots_delete_authenticated"
on public.rhythm_state_snapshots
for delete
to authenticated
using ((select auth.uid()) = user_id);

create or replace function public.snapshot_rhythm_state()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.state is distinct from new.state then
    insert into public.rhythm_state_snapshots (user_id, state, schema_version, created_at)
    values (old.user_id, old.state, old.schema_version, now());

    delete from public.rhythm_state_snapshots
    where id in (
      select id
      from public.rhythm_state_snapshots
      where user_id = old.user_id
      order by created_at desc
      offset 30
    );
  end if;
  return new;
end;
$$;

drop trigger if exists rhythm_states_snapshot on public.rhythm_states;
create trigger rhythm_states_snapshot
after update on public.rhythm_states
for each row
execute function public.snapshot_rhythm_state();

create or replace function public.delete_parsitasks_account()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;
  delete from auth.users where id = current_user_id;
end;
$$;

revoke all on function public.delete_parsitasks_account() from public;
grant execute on function public.delete_parsitasks_account() to authenticated;
