create table if not exists public.rhythm_states (
  user_key text primary key,
  user_id uuid references auth.users (id) on delete cascade,
  state jsonb not null,
  ui_state jsonb not null default '{}'::jsonb,
  schema_version integer not null default 1,
  client_updated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_rhythm_states_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists rhythm_states_updated_at on public.rhythm_states;
create trigger rhythm_states_updated_at
before update on public.rhythm_states
for each row
execute function public.set_rhythm_states_updated_at();

create index if not exists rhythm_states_client_updated_at_idx
on public.rhythm_states (client_updated_at desc);

alter table public.rhythm_states
add column if not exists user_id uuid references auth.users (id) on delete cascade;

drop index if exists public.rhythm_states_user_id_idx;
create unique index rhythm_states_user_id_idx
on public.rhythm_states (user_id);

alter table public.rhythm_states enable row level security;

drop policy if exists "rhythm_states_select_own_key" on public.rhythm_states;
drop policy if exists "rhythm_states_insert_own_key" on public.rhythm_states;

drop policy if exists "rhythm_states_select_authenticated" on public.rhythm_states;
create policy "rhythm_states_select_authenticated"
on public.rhythm_states
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "rhythm_states_insert_authenticated" on public.rhythm_states;
create policy "rhythm_states_insert_authenticated"
on public.rhythm_states
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  and user_key = 'auth:' || (select auth.uid())::text
);

drop policy if exists "rhythm_states_update_authenticated" on public.rhythm_states;
create policy "rhythm_states_update_authenticated"
on public.rhythm_states
for update
to authenticated
using ((select auth.uid()) = user_id)
with check (
  (select auth.uid()) = user_id
  and user_key = 'auth:' || (select auth.uid())::text
);

drop policy if exists "rhythm_states_update_own_key" on public.rhythm_states;

drop policy if exists "rhythm_states_delete_authenticated" on public.rhythm_states;
create policy "rhythm_states_delete_authenticated"
on public.rhythm_states
for delete
to authenticated
using ((select auth.uid()) = user_id);

revoke all on table public.rhythm_states from anon;
revoke all on table public.rhythm_states from authenticated;
grant select, insert, update, delete on table public.rhythm_states to authenticated;

create table if not exists public.rhythm_state_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  state jsonb not null,
  schema_version integer not null,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.rhythm_state_snapshots
add column if not exists summary jsonb not null default '{}'::jsonb;

create index if not exists rhythm_state_snapshots_user_created_idx
on public.rhythm_state_snapshots (user_id, created_at desc);

alter table public.rhythm_state_snapshots enable row level security;

drop policy if exists "rhythm_state_snapshots_select_authenticated" on public.rhythm_state_snapshots;
create policy "rhythm_state_snapshots_select_authenticated"
on public.rhythm_state_snapshots
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "rhythm_state_snapshots_delete_authenticated" on public.rhythm_state_snapshots;
create policy "rhythm_state_snapshots_delete_authenticated"
on public.rhythm_state_snapshots
for delete
to authenticated
using ((select auth.uid()) = user_id);

revoke all on table public.rhythm_state_snapshots from anon;
revoke all on table public.rhythm_state_snapshots from authenticated;
grant select, delete on table public.rhythm_state_snapshots to authenticated;
revoke all on sequence public.rhythm_state_snapshots_id_seq from anon, authenticated;

create or replace function public.snapshot_rhythm_state()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.state is distinct from new.state then
    insert into public.rhythm_state_snapshots (user_id, state, schema_version, summary, created_at)
    values (
      old.user_id,
      old.state,
      old.schema_version,
      jsonb_build_object(
        'tasks', jsonb_array_length(coalesce(old.state -> 'tasks', '[]'::jsonb)),
        'habits', jsonb_array_length(coalesce(old.state -> 'habits', '[]'::jsonb)),
        'goals', jsonb_array_length(coalesce(old.state -> 'goals', '[]'::jsonb)),
        'boardItems', jsonb_array_length(coalesce(old.state -> 'boardItems', '[]'::jsonb)),
        'journalEntries', jsonb_array_length(coalesce(old.state -> 'journalEntries', '[]'::jsonb)),
        'nutritionMeals', jsonb_array_length(coalesce(old.state -> 'nutritionMeals', '[]'::jsonb))
      ),
      now()
    );

    delete from public.rhythm_state_snapshots
    where id in (
      select id
      from public.rhythm_state_snapshots
      where user_id = old.user_id
      order by created_at desc
      offset 30
    );
  end if;
  return new;
end;
$$;

drop trigger if exists rhythm_states_snapshot on public.rhythm_states;
create trigger rhythm_states_snapshot
after update on public.rhythm_states
for each row
execute function public.snapshot_rhythm_state();

revoke all on function public.set_rhythm_states_updated_at() from public, anon, authenticated;
revoke all on function public.snapshot_rhythm_state() from public, anon, authenticated;

create or replace function public.delete_parsitasks_account()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;
  delete from storage.objects
  where bucket_id = 'board-images'
    and (storage.foldername(name))[1] = current_user_id::text;
  delete from auth.users where id = current_user_id;
end;
$$;

revoke all on function public.delete_parsitasks_account() from public, anon, authenticated;
grant execute on function public.delete_parsitasks_account() to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'board-images',
  'board-images',
  false,
  12582912,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "board_images_select_own" on storage.objects;
create policy "board_images_select_own"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'board-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "board_images_insert_own" on storage.objects;
create policy "board_images_insert_own"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'board-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "board_images_update_own" on storage.objects;
create policy "board_images_update_own"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'board-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'board-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

drop policy if exists "board_images_delete_own" on storage.objects;
create policy "board_images_delete_own"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'board-images'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);
